### ISSUE TITLE
Alternative Base58 implementation

### ISSUE THREAD

**Issue by roshii** [gdkrmr/Base58.jl#1]
Would you please create an alt branch so that we can test on a common base?

See [fork](https://github.com/roshii/Base58.jl/tree/alt_testing) for reference and to start with - I blondy duplicated code to compare implementation

**Comment by gdkrmr** [comment]
Why not put this in a submodule for now? Then you can do:

```julia
Base58.base58encode(...)
Base58.alt.base58encode(...)
```

**Comment by roshii** [comment]
Good one, I'll amend code accordingly

**Comment by gdkrmr** [comment]
btw, there are some performance tests I wrote in `test/perf.jl`

**Comment by roshii** [comment]
My first performance test were indeed a blond copy of your perf.jl
I have now implemented a submodule and amended performance test, see `test/perf_vs_alt.jl`

As far as encoding is concerned, my implementation seem to always be quicker, the more bits, the more differences:
```
16 bits average encoding Δ: -50.0 ns
32 bits average encoding Δ: -50.0 ns
64 bits average encoding Δ: -52.0 ns
128 bits average encoding Δ: -66.0 ns
256 bits average encoding Δ: -89.0 ns
512 bits average encoding Δ: -139.0 ns
1024 bits average encoding Δ: -227.0 ns
2048 bits average encoding Δ: -355.0 ns
4096 bits average encoding Δ: -350.0 ns
```

When we look at decoding, thing are different and we see a switch in favor of your implementation above 512 bits

```
16 bits average decoding Δ: 0.0 ns
32 bits average decoding Δ: -0.0 ns
64 bits average decoding Δ: -2.0 ns
128 bits average decoding Δ: -1.0 ns
256 bits average decoding Δ: -5.0 ns
512 bits average decoding Δ: -6.0 ns
1024 bits average decoding Δ: 22.0 ns
2048 bits average decoding Δ: 152.0 ns
4096 bits average decoding Δ: 764.0 ns
```

Should we just replace your encode function by mine?
Should we add a conditional in the decode function that would use my implementation up to 512 bits?

Maybe more/different benchmarking is required? On different machines if that can have an impact?

**Comment by roshii** [comment]
I also just noticed that your base58decode does return an Array while mine returns a String which makes it easier to handle within a Bitcoin node implementation and makes it human readable, the basis of base58 in my opinion.

What is your motivation for returning an Array instead?

**Comment by gdkrmr** [comment]
can you give me the code you are using for your benchmarks?

**Comment by roshii** [comment]
https://github.com/roshii/Base58.jl/blob/master/test/perf_vs_alt.jl

**Comment by gdkrmr** [comment]
I see that you are using `@elapsed`, this measures runtime + precompile time if you call a function for the first time. For benchmarking it is better to use `@btime` or `@benchmark` from `BenchmarkTools.jl`.

**Comment by gdkrmr** [comment]
>  also just noticed that your base58decode does return an Array while mine returns a String which makes it easier to handle within a Bitcoin node implementation and makes it human readable, the basis of base58 in my opinion.
> 
> What is your motivation for returning an Array instead?

Let me check why I did it this way. I currently don't remember the rationale behind it and I wrote this package quite a long time ago.

**Comment by gdkrmr** [comment]
Here are my results. I took a look at `perf_vs_alt.jl` and ran the `for`-loop two times to account for precompilation. You do `original - alternate` , so do negative values mean that my implementation is faster?

```
16 bits average encoding Δ: -11.0 ns
32 bits average encoding Δ: -10.0 ns
64 bits average encoding Δ: -11.0 ns
128 bits average encoding Δ: -16.0 ns
256 bits average encoding Δ: -25.0 ns
512 bits average encoding Δ: -49.0 ns
1024 bits average encoding Δ: -69.0 ns
2048 bits average encoding Δ: -110.0 ns
4096 bits average encoding Δ: -707.0 ns

16 bits average decoding Δ: -0.0 ns
32 bits average decoding Δ: -0.0 ns
64 bits average decoding Δ: -0.0 ns
128 bits average decoding Δ: -1.0 ns
256 bits average decoding Δ: -1.0 ns
512 bits average decoding Δ: 1.0 ns
1024 bits average decoding Δ: 8.0 ns
2048 bits average decoding Δ: 44.0 ns
4096 bits average decoding Δ: 207.0 ns
```

**Comment by gdkrmr** [comment]
It seems the other way round, my implementation is faster for small data, but the decoding gets slow if the data gets larger. That said, I think your implementation can still be optimized quite a bit.

```julia
function perf(nbits)
    nbytes = ceil(Int, nbits / 8)
    data = [rand(UInt8) for i in 1:nbytes]

    enc_data = Base58.base58encode(data)
    dec_data = Base58.base58decode(enc_data)

    @btime Base58.base58encode($data);
    @btime Base58.alt.base58encode($data);
    @btime Base58.base58decode($enc_data);
    @btime Base58.alt.base58decode($enc_data);
    return nothing
end
```

Output:
```julia
julia> perf(4096)
  457.549 μs (2 allocations: 1.59 KiB)
  481.581 μs (8619 allocations: 343.20 KiB)
  270.287 μs (2 allocations: 1.22 KiB)
  55.944 μs (1400 allocations: 292.44 KiB)

julia> perf(256)
  2.099 μs (2 allocations: 256 bytes)
  25.276 μs (562 allocations: 12.74 KiB)
  1.320 μs (2 allocations: 256 bytes)
  2.148 μs (88 allocations: 3.41 KiB)

```

**Comment by gdkrmr** [comment]
Also your `base58decode` is wrong:
1) it returns a String
2) `data == base58decode(base58encode(data))` must be true for any `UInt8[...]`

```julia
nbits = 256
nbytes = ceil(Int, nbits / 8)
data = [rand(UInt8) for i in 1:nbytes]

enc_data = Base58.base58encode(data)
dec_data = Base58.base58decode(enc_data)

@assert data == dec_data

enc_data = Base58.alt.base58encode(data)
dec_data = Base58.alt.base58decode(enc_data)

codeunits(dec_data)
@assert data == codeunits(dec_data)
```

**Comment by roshii** [comment]
> You do original - alternate , so do negative values mean that my implementation is faster?

Oups, indeed, negative means yours is faster

The output of `perf(nbits)` is clear as well, alternative decode implementation can be beneficial in terms of processing speed but at the expense of memory consumption.
Now, as far as optimization in concerned, I do not have the Julia expertise to do that (yet), feel free, I am definitely curious to see how you'd do that ;)

That being said, I'll add your Basa58 package as a dependency for Bitcoin.jl - which clearly works better as far as bitcoin address are concerned.

**Comment by gdkrmr** [comment]
Your `base58encode` seems faster for 8192 bits and more. Your `base58decode` simply does not what it is supposed to. The problem with `BigInt` is that they need to allocate memory which has a lot of overhead and as far as I know, Julia does not provide functions that mutate `BigInt` in-place without allocating memory.

Thanks for taking a look at this, I am happy that someone finds my code useful! :-)

**Comment by gdkrmr** [comment]
If you want to give it another shot, you could try `string(x, base = 58) |> codeunits`, I think you would only have to switch the alphabet for encoding. There is also `parse(x, base = 58)`.

**Comment by roshii** [comment]
> Also your `base58decode` is wrong:
> 
>     1. it returns a String
> 
>     2. `data == base58decode(base58encode(data))` must be true for any `UInt8[...]`

Right, now I see your rationale for returning an Array :)
My implementation was tailor made to return a String that I can use for Bitcoin.jl. Strictly speaking it is indeed wrong, ` 2.` must definitely be true.  But I know realize that a simple  `String(base58encode(data))` would just work fine for what I assume was a decode function...

**Comment by roshii** [comment]
> Your `base58encode` seems faster for 8192 bits and more. Your `base58decode` simply does not what it is supposed to. The problem with `BigInt` is that they need to allocate memory which has a lot of overhead and as far as I know, Julia does not provide functions that mutate `BigInt` in-place without allocating memory.

Julia definitely does allocate a lot of memory from BigInt, which I'll have to be careful about.
I'm also not sure if someone would encode 8192+ bits word to base58, in other word, is it worth to add lines to your code to account for this?

> If you want to give it another shot, you could try string(x, base = 58) |> codeunits, I think you would only have to switch the alphabet for encoding. There is also parse(x, base = 58).

Thanks for the tip, it looks faster from below quick test, but would not come handy for Bitcoin since one has to manipulate bytes to serialize data.

```
function bitaddress()
    raw = hex2bytes("005dedfbf9ea599dd4e3ca6a80b333c472fd0b3f69")
    want = "19ZewH8Kk1PDbSNdJ97FP4EiCjTRaZMZQA"
    println(String(base58checkencode(raw)) == want)
end
```
```
julia> @btime string(n, base=58)
  2.319 μs (7 allocations: 232 bytes)
"1Hq757HBMRKpmfAUMgaASOOOkW5N"

julia> perf(256)
  6.482 μs (2 allocations: 256 bytes)
```

> Thanks for taking a look at this, I am happy that someone finds my code useful! :-)

Thanks for looking at my code as well and thanks for all tips and suggestions, I'm not two month into Julia and learning everyday :)
